-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "langEnum" AS ENUM('de-de', 'en-us', 'es-mx', 'fr-fr', 'id-id', 'it-it', 'ja-jp', 'ko-kr', 'pt-br', 'ru-ru', 'th-th', 'vi-vn', 'zh-cn', 'zh-tw');--> statement-breakpoint
CREATE TABLE "accounts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"dcid" text NOT NULL,
	"added_on" timestamp with time zone DEFAULT now() NOT NULL,
	"nickname" text NOT NULL,
	"account_token" text NOT NULL,
	"hg_id" text NOT NULL,
	"user_id" text NOT NULL,
	"role_id" text NOT NULL,
	"channel_id" text NOT NULL,
	"server_type" text NOT NULL,
	"server_id" text NOT NULL,
	"server_name" text NOT NULL,
	"is_private" boolean DEFAULT false NOT NULL,
	"enable_notif" boolean DEFAULT true NOT NULL,
	"enable_signin" boolean DEFAULT true NOT NULL,
	"enable_redeem" boolean DEFAULT true NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"short_id" smallint DEFAULT 1 NOT NULL,
	CONSTRAINT "accounts_dcid_short_id_key" UNIQUE("dcid","short_id")
);
--> statement-breakpoint
ALTER TABLE "accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "ef_attempted_codes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ef_attempted_codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"aid" uuid NOT NULL,
	"code" text NOT NULL,
	"attempted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" smallint NOT NULL,
	"last_attempted_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ef_attempted_codes_aid_code_key" UNIQUE("aid","code")
);
--> statement-breakpoint
ALTER TABLE "ef_attempted_codes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "ef_codes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ef_codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" text NOT NULL CONSTRAINT "ef_codes_code_key" UNIQUE,
	"rewards" text[],
	"notes" text[]
);
--> statement-breakpoint
ALTER TABLE "ef_codes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "events" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"dcid" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"source" text NOT NULL,
	"action" text NOT NULL,
	"metadata" jsonb,
	"aid" uuid,
	CONSTRAINT "event_pkey" PRIMARY KEY("id")
);
--> statement-breakpoint
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"dcid" text PRIMARY KEY,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_banned" boolean DEFAULT false NOT NULL,
	"enable_notif" boolean DEFAULT true NOT NULL,
	"is_private" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"lang" "langEnum" DEFAULT 'en-us'::"langEnum" NOT NULL,
	"isPremium" boolean DEFAULT false NOT NULL,
	"enable_reminder" boolean DEFAULT false NOT NULL,
	"allow_data" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE UNIQUE INDEX "accounts_one_primary_per_user" ON "accounts" ("dcid") WHERE is_primary;--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_dcid_fkey" FOREIGN KEY ("dcid") REFERENCES "users"("dcid") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "event_dcid_fkey" FOREIGN KEY ("dcid") REFERENCES "users"("dcid") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_aid_fkey" FOREIGN KEY ("aid") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "ef_attempted_codes" ADD CONSTRAINT "ef_attempted_codes_aid_fkey" FOREIGN KEY ("aid") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
*/